# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchrail" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "3a850d2da87ca946784e57bc458b9a1781d308f346d9fda0f273d95111199f87"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "866de1b664b98036ee65cd4025c609040088d4fdf51fb1420eeffb24fdb25960"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b3c4707ec282e4560d4dba070902f892c07134df6c4e61ca13671bb2edbc8ec"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "df0f3a401ec33bda3d867a6ea9a8a5411fe0b4234a233eabc2ced2470d907c43"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  name "switchrail"
  desc "TUI orchestrator for coding agents"
  homepage "https://github.com/nekstep/switchrail-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchrail"
  binary "switchrail-askpass-deny"

  # No zap stanza required

end
