# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchrail" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "dcc6735edb5b54ca087972e396b8b7e8b4d3cd68d51299ba0e92ccb0c0ee822f"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "4a24f3e75ffccea0f4128db8ec0dff251dc93bd7d4085262ebfe7082cfd83f42"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "04f7c0b037f2bb83fdd2983efa0548ad044ed0fcfbe0df3964b1a631138f3ecd"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "7afc3b78833a027abb7fd2cde888768aa9dde1027052aad6dcde0b613dd59726"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  name "switchrail"
  desc "TUI orchestrator for coding agents"
  homepage "https://github.com/nekstep/switchrail-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchrail"
  binary "switchrail-askpass-deny"

  # No zap stanza required

end
