# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchrail" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "69310a97fab0424e3b033e5c4bf8a9cc91bb97013ee417e2803661a44cb3ecfb"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "ada999532bb751b1a9348935ae253db83d913c30754766041b61ee75599e74ba"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Darwin_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "41447f0595a1bed184f25bb24d11bf8a5bfc961eb55bb6ceb17f5068804761c5"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_x86_64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
    on_arm do
      sha256 "2db48a900f53c0af2532c7a4f4142455f6c0be312768c0a84e8f3783f7a6f9ef"
      url "https://github.com/nekstep/switchrail-releases/releases/download/v#{version}/switchrail_Linux_arm64.tar.gz",
        verified: "github.com/nekstep/switchrail-releases/"
    end
  end

  name "switchrail"
  desc "TUI orchestrator for coding agents"
  homepage "https://github.com/nekstep/switchrail-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchrail"
  binary "switchrail-askpass-deny"

  # No zap stanza required

end
